### ISSUE TITLE
errors installing with npm

### ISSUE THREAD

**Issue by eurekaa** [eventualbuddha/ast-util#3]
Hi,
i get an error with npm install: "no compatible version found: ast-types@'^0.4.1"

I saw that version exists, i don't know why this error.
Can you check please?

Thanks.

**Comment by eventualbuddha** [comment]
What version of node? What version of npm? (i.e. what's the output of `npm version`).

**Comment by eurekaa** [comment]
node: 0.10.9
npm: 1.2.24

**Comment by eurekaa** [comment]
I got the same error with package 'jslint'.
Solved updating nodejs and npm.

I see that there was a common thing, the '^' character in defining dependecy version, maybe not or maybe this char is not compatible with previous npm version.

Just for your info.

**Comment by eurekaa** [comment]
As i thought it is the `^` operator.
You should add this dependency in your package.json to avoid it.

```
"engines": {
        "node": ">=0.10.13"
 }
```

**Comment by eventualbuddha** [comment]
I've released v0.4.0 with a fix for this.
